package bkap.entity;
// Generated Oct 26, 2020 8:40:34 PM by Hibernate Tools 4.3.1



/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private OrderDetailId id;
     private OrderPro orderPro;
     private ProductDetail productDetail;
     private Integer quantity;

    public OrderDetail() {
    }

	
    public OrderDetail(OrderDetailId id, OrderPro orderPro, ProductDetail productDetail) {
        this.id = id;
        this.orderPro = orderPro;
        this.productDetail = productDetail;
    }
    public OrderDetail(OrderDetailId id, OrderPro orderPro, ProductDetail productDetail, Integer quantity) {
       this.id = id;
       this.orderPro = orderPro;
       this.productDetail = productDetail;
       this.quantity = quantity;
    }

    public OrderDetail(ProductDetail proDe, OrderDetail orde, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public OrderDetailId getId() {
        return this.id;
    }
    
    public void setId(OrderDetailId id) {
        this.id = id;
    }
    public OrderPro getOrderPro() {
        return this.orderPro;
    }
    
    public void setOrderPro(OrderPro orderPro) {
        this.orderPro = orderPro;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


