package bkap.entity;
// Generated Oct 26, 2020 8:40:34 PM by Hibernate Tools 4.3.1



/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId  implements java.io.Serializable {


     private int productDetailId;
     private int orderId;

    public OrderDetailId() {
    }

    public OrderDetailId(int productDetailId, int orderId) {
       this.productDetailId = productDetailId;
       this.orderId = orderId;
    }
   
    public int getProductDetailId() {
        return this.productDetailId;
    }
    
    public void setProductDetailId(int productDetailId) {
        this.productDetailId = productDetailId;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderDetailId) ) return false;
		 OrderDetailId castOther = ( OrderDetailId ) other; 
         
		 return (this.getProductDetailId()==castOther.getProductDetailId())
 && (this.getOrderId()==castOther.getOrderId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductDetailId();
         result = 37 * result + this.getOrderId();
         return result;
   }   


}


