package bkap.entity;
// Generated Oct 26, 2020 8:40:34 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Rom generated by hbm2java
 */
public class Rom  implements java.io.Serializable {


     private int romId;
     private String romName;
     private Boolean romStatus;
     private Set productDetails = new HashSet(0);

    public Rom() {
    }

	
    public Rom(int romId) {
        this.romId = romId;
    }
    public Rom(int romId, String romName, Boolean romStatus, Set productDetails) {
       this.romId = romId;
       this.romName = romName;
       this.romStatus = romStatus;
       this.productDetails = productDetails;
    }
   
    public int getRomId() {
        return this.romId;
    }
    
    public void setRomId(int romId) {
        this.romId = romId;
    }
    public Serializable getRomName() {
        return this.romName;
    }
    
    public void setRomName(String romName) {
        this.romName = romName;
    }
    public Boolean getRomStatus() {
        return this.romStatus;
    }
    
    public void setRomStatus(Boolean romStatus) {
        this.romStatus = romStatus;
    }
    public Set getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set productDetails) {
        this.productDetails = productDetails;
    }




}


